### ISSUE TITLE
Dependency "PadWalker" not installed via cpanm

### ISSUE THREAD

**Issue by PopeFelix** [stevan/p5-Moxie#2]
`cpanm Moxie` failed the first time; had to `cpanm PadWalker` to get it installed. See attached build.log
[build.log.txt](https://github.com/stevan/p5-Moxie/files/1114016/build.log.txt)

**Comment by stevan** [comment]
Should be fixed now in 0.02

**Comment by stevan** [comment]
Thanks :)
